### ISSUE TITLE
Generating annotations

### ISSUE THREAD

**Issue by ashwiniraja** [jolilj/CascadedCNNFaceDetection#2]
Hi, could you please tell me how you generated the annotations.txt file and if there is a script to generate that from any dataset? Can I test this on a different dataset ?

**Comment by jolilj** [comment]
It's been a while since I looked at this project so I might be misremembering :) The annotations we used are available together with the dataset. You can definitely test it on a different dataset as long as you translate the annotations from that set to the needed label format for our cnn. Have a look in imageloader.py where this is done.

**Comment by ashwiniraja** [comment]
Thank you !
